export const getAssetBaType = {
    logo: "logo",
    "business card": "bizcard",
    resume: "resume",
    cv: "resume",
    "xpo 0ffice": "xpo-office",
    'brand book': "brand-book",
    "greeting card": "corporate-greeting-card",
    "corporate identity": "corporate-identity",
    "presentation": "corporate-presentation",
    "corporate presentation": "corporate-presentation",
    "corporate profile": "corporate-profile",
    "form": "bizform",
    "digital form": "bizform",
    "email signature": "email-signature",
    flyer: "flyers-posters-banner",
    poster: "flyers-posters-banner",
    banner: "flyers-posters-banner",
    banners: "flyers-posters-banner",
    "id card": "id-card",
    "invoice": "invoices-quotes-receipts",
    "quote": "invoices-quotes-receipts",
    "receipt": "invoices-quotes-receipts",
    letterhead: "letterhead",
    portfolio: "portfolio",
    pricelist: "pricelist",
    "profile card": "profile-card",
    video: "video",
  };